title: "Sthitaprajna Biswal | Cybersecurity Engineer"
email: "sthitabiswal2002@gmail.com"
description: >-
  Cybersecurity Expert with 2+ years delivering measurable risk reduction across web applications, REST/SOAP APIs, mobile apps, cloud, and Kubernetes environments in FinTech.
url: "https://sthitaprajna-biswal.github.io"
baseurl: ""
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
author:
  name: "Sthitaprajna Biswal"
  avatar: "https://github.com/Sthitaprajna.png"
  bio: "Cloud Security Expert | AppSec Professional | Red Team Practitioner"
  location: "Bhubaneswar, India"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/sthitaprajna-biswal-0175b7171"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Sthitaprajna"
markdown: kramdown
highlighter: rouge
paginate: 5
include:
  - _pages
collections:
  projects:
    output: true
